export enum enumProductStatus {
    PRODUCT_STATUS_ACTIVE = 0,
    PRODUCT_STATUS_CLOSED,
    PRODUCT_STATUS_FORGOT,
    PRODUCT_STATUS_BANNED,
    PRODUCT_STATUS_DELETED,
}
export enum enumProductModerationStatus {
    PRODUCT_MODERATION_STATUS_VERIFYING = 0,
    PRODUCT_MODERATION_STATUS_VERIFIED,
    PRODUCT_MODERATION_STATUS_PROBLEM
}