FROM node:20.11.1

COPY ./build ./usr/src/iboot/frontend/moderation/build
WORKDIR /usr/src/iboot/frontend/moderation

EXPOSE 12005

RUN npm install -g serve
CMD [ "serve", "-s", "build", "-l", "12005" ]